export const initial_board = {

    "black-rook1": "a7",
    "black-knight1": "a6",
    "black-bishop1": "b6",
    "black-queen": "b7",
    "black-king": "a8",
    "black-bishop2": "c8",
    "black-knight2": "c7",
    "black-rook2": "b8",
    "black-pawn1": "a5",
    "black-pawn2": "d8",
    "black-pawn3": "c6",
    "black-pawn4": "d6",
    "black-pawn5": "b5",
    "black-pawn6": "d7",
    "black-pawn7": "c5",
    "black-pawn8": "d5",
    "white-rook1": "g1",
    "white-knight1": "f2",
    "white-bishop1": "f1",
    "white-queen": "g2",
    "white-king": "h1",
    "white-bishop2": "g3",
    "white-knight2": "h3",
    "white-rook2": "h2",
    "white-pawn1": "e1",
    "white-pawn2": "f3",
    "white-pawn3": "h4",
    "white-pawn4": "g4",
    "white-pawn5": "f4",
    "white-pawn6": "e4",
    "white-pawn7": "e3",
    "white-pawn8": "e2",

};